### ISSUE TITLE
Last characters on line does not show in some cases

### ISSUE THREAD

**Issue by mgnslndh** [RolandPheasant/TailBlazer#139]
Not sure if this is some edge case but I recently observed the following behaviour:

The last line in the log fail looks like this:
```
2016-06-15 14:27:10.923 +02:00 [Verbose] [9] Changing configuration "YarnDetectors.Needle" from YarnDetector { StartDelay: 100, Inhibit: 1, Enabled: False, Sensitivity: 0, Filter: 100 } to YarnDetector { StartDelay: 9999, Inhibit: 100, Enabled: True, Sensitivity: 100, Filter: 9998 }
```

And what actually is displayed looks like this:

![image](https://cloud.githubusercontent.com/assets/1139118/16079955/795941de-3306-11e6-8f4f-9cd496d27729.png)

`Filter 99` is the last characters displayed on the line but I was expecting `Filter: 9998 }`

**Comment by RolandPheasant** [comment]
This is fixed but not released. Have you tried to build from the latest master branch?

**Comment by mgnslndh** [comment]
I pulled from master but I can still reproduce the behaviour. Wierd.

I also noticed that sometimes when I scroll to the right and then scroll up/down I get to a situation where the horizontal scrollbar disappear but the viewport is not positioned at X = 0. See screenshot: 

![image](https://cloud.githubusercontent.com/assets/1139118/16119208/c3317536-33da-11e6-8041-43c394253303.png)

**Comment by RolandPheasant** [comment]
Have you got a file or a bit of a file which can be used to repeatedly repeat it?
